### PR TITLE
First proposal for change of Swal2 logo

### PR DESCRIPTION
**Pull request by serenaperora**
This include: 

* New logo (in SVG) 
* New SweetAlert2 png for the logo text 
* Bouncing animation for logo
* Change of font for `h1` and `h2` tags (using [Monserrat from Google fonts](https://fonts.google.com/specimen/Montserrat), which is the closest to the logo text)

TO DO: 
- [x] Add bouncing path 

image

- [x] Improve SVG style integration (currently part of the animation is in the CSS and part is embedded in SVG)
- [x] There is an issue with refreshing the page: the SVG animation doesn't get restarted

image

- Test on different browsers / screen sizes: 
  - Chrome 
    - - [x] on Window
    - - [x] on Linux
    - - [x] on macOS
    - - [x] On Android
    - - [x] On IOS
  - Firefox 
    - - [x] on Window
    - - [x] on Linux
    - - [x] on macOS
    - - [x] On Android
    - - [x] On IOS
  - Safari 
    - - [x] on macOS
    - - [x] On IOS
  - - ~~IE11 (on Window)~~
  - - [x] Edge (on Window)

### CODE REVIEW

**Comment by serenaperora** [comment]
@limonte this is a first proposal for the new logo. There's still a number of things to do (e.g. color palette, match fonts, make logo responsive, etc), but we just wanted to check with you if you like the animation and the positioning of the logo.

**Comment by limonte** [comment]
Looks great so far! :muscle: :muscle: :muscle: 

Animations are neat! :1st_place_medal:

**Comment by gverni** [comment]
Sorry @limonte for the delay on this PR. We are still _battling_ with making the bouncing path appears. We may have to drop it for now...

**Comment by limonte** [comment]
No problem @gverni 

The new logo can wait as long as needed. I know how hard is to predict when the inspiration will come :)

**Comment by gverni** [comment]
>  I know how hard it is to predict when the inspiration will come :)

Inspiration finally came @limonte 😄 We just updated the animation adding the bouncing track. Before we start testing on different browsers / sizes, can you have a look and let us know if you like it? Any suggestion is more than welcome!!

**Comment by gverni** [comment]
@limonte did you get a chance to look at the new animation? I just wanted your opinion before I start the browser testing...

**Comment by limonte** [comment]
> did you get a chance to look at the new animation? I just wanted your opinion before I start the browser testing...

LGTM!

**Comment by gverni** [comment]
> sorry for missing the previuos comment, thanks for pinging me again :)sorry for missing the previuos comment, thanks for pinging me again :)

No worries... I've seen you had a pretty busy weekend :wink:
I'll start browsers testings and report back in 1 or 2 days.

**Comment by gverni** [comment]
Browser testing is looking good at the moment. I'll have to wait until Monday to perform testing on windows. 

On small screens (i.e. smartphone) donut and the path are a bit too high (one of the donut _hair_ is touching the octocat). I'll have to tweak it a bit... 

image

**Comment by gverni** [comment]
Sorry for slow update (bit of hectic period at work). On windows all the browsers work ok, except for IE11: 

image

That definitely needs a bit of work :cry:

**Comment by limonte** [comment]
@gverni don't bother yourself with IE11. It is our responsibility to make SweetAlert2 by itself work in it and demonstrate that it's working. But we do not have any responsibility to make the complex animated logo work in IE11.

I believe 0.56% of IE users will forgive and understand us for broken logo animation :)

image

**Comment by gverni** [comment]
Thanks @limonte! I further optimized and clean-up the embedded donut SVG. I think I'm done for now... As you suggested, I'll try to fix IE11 later on if I get some time. If you and @serenaperora are fine, I think we are ready to merge here...

**Comment by limonte** [comment]
This PR has conflicts and in order to save @serenaperora from the painful process of rebasing and resolving conflicts, I copied the rebased PR with some coding style fixes to #96

**Pull request closed without merging**
