### PR TITLE
Chore/add custom container class

### PR DESCRIPTION
**Pull request by gverni**
Added example for customer container class. As an example, I added a red flashing border to the swal container. 

I should have probably added an example related to https://github.com/sweetalert2/sweetalert2/issues/1244 but in order to do that I needed to add a container div somewhere and I didn't want to make the documentation page heavier / more complex. 

I still think it would make sense create some additional pages with advanced use cases and documentation (see https://github.com/sweetalert2/sweetalert2.github.io/issues/43)

### CODE REVIEW

**Comment by limonte** [comment]
I don't think an example of `customContainerClass` is needed, its usage and description is straight forward. Just docs would be enough.

**Comment by limonte** [comment]
> No problem, do you want me to remove the one I added then?

Please do, sorry about the inconvenience. In the future, I will try to open issues with a clear description of the desired outcome for each PR.

**Comment by gverni** [comment]
No problem at all!! It's always fun to try to create new examples ;-) 

Let me close this PR and open a new cleaner one...

**Comment by gverni** [comment]
Closing this in favor of https://github.com/sweetalert2/sweetalert2.github.io/pull/56

**Pull request closed without merging**
