### PR TITLE
[WIP] Dev/docusaurus

### LINKED ISSUE #1: Features and libraries for code samples
https://github.com/sweetalert2/sweetalert2/issues/711#issuecomment-355639796

> Idea: It would be cool to use something like Codemirror for examples, but where you can execute/modify/execute the code. I absolutely <3 Semantic UI React's documentation site for this. https://react.semantic-ui.com/elements/button#button-example-labeled There are some other nifty features for the code samples there too.

All those nifty features would be nice-to-haves, but I think we really should have something that de-duplicates the code for viewing vs executing.

Anyone have a suggestion for a library to leverage for this?

### LINKED ISSUE #5: Idea: Pull documentation from other repos
The idea is to have the build process here pull markdown from each library repo, for the topics like #configuration and #methods which are duplicated here and (1) are updated more frequently and (2) don't have a use for js/dhtml .

This would eliminate the duplication of effort and fix a lot of the pain of the disadvantage i describe here - https://github.com/sweetalert2/sweetalert2/issues/711#issuecomment-355611512

We would probably want to split up our documentation into multiple `.md` files though.

### PR DESCRIPTION
**Pull request by zenflow**
Closes #1 and #2 

Try it out @ https://zenflow.github.io/sweetalert2.github.io/

Still todo:

- pull markdown docs from core repo, to close #5, and actual markown documentation (copied from old site)
- "edit this page" configuration
- highlighting the current section in the right-side menu
- Donate section
- Team section? maybe like [this](https://babeljs.io/team)
- maybe a little more style & love in general?
- ?
- delete the old/ dir

After publishing
- register with Algolia to enable search, since in a sense "search" will be broken on this site.. before you could ctrl+f but now the docs are split up onto multiple pages and you can't ctrl+f.

### CODE REVIEW

**Comment by zenflow** [comment]
The build passes until this `awesome_bot` thing at the end

**Comment by zenflow** [comment]
Oh @limonte, only the basic carbon ads are installed. For the ads in the footers... I was never able to actually see these although they seemed to work for others. Maybe you could handle it? 

Ideally we would extend the base `Swal` and name it just `Swal` (in the global namespace) so in the examples it looks like we're using the base `Swal`. But it needs to act exactly like the base Swal (i.e. no need for `new` keyword), so maybe we should expose `withNoNewKeyword` from the core library so we can use it here..

**Comment by zenflow** [comment]
Awesome @acupajoe thanks for the kind words

> I'd say that examples need to have text above them explaining what the feature is. The page feels like it's lacking otherwise. Really liking the example code running.

You referring to the examples in the examples section right? The content (example code and description used for the heading) is just copied and pasted from the old site. I still have to copy the rest, and I figure I should stick to just copying/translating the old content, and we can follow up on revising & improving the content later in separate PRs.

**Comment by zenflow** [comment]
Ok, there are some issues running on IE11 and Edge, some of them upstream in Docusaurus and https://github.com/zenflow/example-code, fixes underway.

Another issue: I'm seeing my scroll position jump all around when I scroll down as much as I can and click an "execute" button..I have no idea why.. is this related to some behavior of SweetAlert2?

**Comment by limonte** [comment]
> Another issue: I'm seeing my scroll position jump all around when I scroll down as much as I can and click an "execute" button..I have no idea why.. is this related to some behavior of SweetAlert2?

This is because of incorrect body height `100vh` coming from `main.css`.

**Comment by limonte** [comment]
> Closes #1

From #1 

> Idea: It would be cool to use something like Codemirror for examples, but where you can execute/modify/execute the code.

How can users modify code snippets?

**Comment by zenflow** [comment]
> How can users modify code snippets?

They can't, yet, but that feature is effectively coming soon in [example-code](https://github.com/zenflow/example-code) (which is being used here) in the form of links to open the code in jsfiddle and those kinds of websites. I don't want to support inline editing because it's a lot of overhead for something that's better off left to one of the many awesome already-existing solutions for playing with code examples in the browser.

**Comment by zenflow** [comment]
@limonte Does it look alright so far? If so I'll continue on the TODOs

**Comment by limonte** [comment]
> But I override that style with height: 100% and I still see the effects. It's most pronounced on the longest page: https://zenflow.github.io/sweetalert2.github.io/docs/examples-advanced.html

There's another CSS issue in Docusaurus:

```css
.navPusher {
  height: 100%;
}
```

> I'm not sure what the normal css setting for this would/should be, but I was also unaware that SweetAlert2 required a "normal" height style on the body element.. seems to be an issue with SweetAlert2, since we shouldn't impose this kind of requirement on users, right?

Well, setting height `100vh` or `100%` on the document with height bigger than viewport is incorrect. In both cases `height` should be replaced with `min-height`. I just sent the PR to Docusaurus: https://github.com/facebook/Docusaurus/pull/556

**Comment by limonte** [comment]
> Does it look alright so far? If so I'll continue on the TODOs

Yes, it does. I'm very happy about the new codebase. There are some small issues like IE11, but the concept by itself is lovely, feel free to go ahead with the rest of items in the todo list. I will be happy to merge this PR once it's completed. 

Ps. I'm in the vacation mode right now, apologies for delayed replies and CRs.

**Comment by limonte** [comment]
I changed my mind. Let's not require from our contributors the knowledge of React, Docusaurus, markdown, whatnot just because we can.

There are no real issues we will solve with bringing new "cool" technologies. Nothing is better than good old HTML.

The current solution is well tested and works perfectly on all devices, I don't have time to do the same work for the new solution. Contributors seem to be busy, I can't and I shouldn't count on them.

[React isn't easy](http://bradfrost.com/blog/post/my-struggle-to-learn-react/) even if some of us feel so. The current state of the front-end is terrible. Let's admit it and patiently wait for the bright future. Until then, 

image

**Comment by zenflow** [comment]
@limonte Your comment is more about the issue than the solution, so it really belongs in that discussion.. I'll copy it there

**Pull request closed without merging**
